shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'packages/*'
  - docs
  - .histoire
overrides:
  minimatch@>=5.0.0 <5.1.8: '>=10.2.3'
  picomatch@<2.3.2: '>=4.0.7'
  rollup@>=3.0.0 <3.30.0: '>=4.63.1'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  svgo@>=3.0.0 <3.3.3: '>=4.1.0'
patchedDependencies:
  vitepress: patches/vitepress.patch
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
