name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

  pull_request:
    paths:
      - 'packages/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup (Install node & pnpm)
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm --filter reka-ui build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: reka-ui-dist
          path: packages/core/dist
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup (Install node & pnpm)
        uses: ./.github/actions/setup

      - name: Test (with coverage)
        run: pnpm --filter reka-ui test:coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: packages/core/coverage
          retention-days: 7

  size:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup (Install node & pnpm)
        uses: ./.github/actions/setup

      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: reka-ui-dist
          path: packages/core/dist

      - name: Check bundle size
        run: pnpm --filter reka-ui size
